/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/sanity/extract.json
export type CarePlan = {
  _id: string;
  _type: 'carePlan';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  excerpt?: string;
  pricePerMonth?: number;
  inclusive?: Array<{
    title?: string;
    body?: string;
    _key: string;
  }>;
  exclusive?: Array<string>;
  isPremium?: boolean;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type Page = {
  _id: string;
  _type: 'page';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  type?: 'main' | 'utility';
  seo?: Seo;
  body?: BlockContent;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote';
      listItem?: 'bullet';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }
  | ({
      _key: string;
    } & ImageWithAlt)
>;

export type Seo = {
  _type: 'seo';
  metaTitle?: string;
  metaDescription?: string;
  ogImage?: ImageWithAlt;
  noIndex?: boolean;
};

export type Capability = {
  _id: string;
  _type: 'capability';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  value?: number;
};

export type Faqs = {
  _id: string;
  _type: 'faqs';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  stage?: number;
  faqs?: Array<
    {
      _key: string;
    } & Faq
  >;
};

export type Project = {
  _id: string;
  _type: 'project';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  type?: Array<string>;
  mainImage?: ImageWithAlt;
  startedAt?: string;
  endedAt?: string;
  excerpt?: string;
  body?: BlockContent;
  seo?: Seo;
  previewUrl?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type ImageWithAlt = {
  _type: 'imageWithAlt';
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
};

export type Service = {
  _id: string;
  _type: 'service';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  title?: string;
  body?: string;
  color?: string;
};

export type SiteSetting = {
  _id: string;
  _type: 'siteSetting';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName?: string;
  primaryLogo?: ImageWithAlt;
  socialLinks?: Array<
    {
      _key: string;
    } & SocialLink
  >;
  seo?: Seo;
  navLinks?: Array<
    {
      _key: string;
    } & NavLink
  >;
  footerColumns?: Array<
    {
      _key: string;
    } & FooterColumn
  >;
  footerText?: string;
  contactInfo?: {
    street?: string;
    zip?: string;
    city?: string;
    state?: string;
    country?: string;
    email?: string;
  };
};

export type FooterColumn = {
  _type: 'footerColumn';
  title?: string;
  links?: Array<{
    label?: string;
    href?: string;
    _key: string;
  }>;
};

export type NavLink = {
  _type: 'navLink';
  label?: string;
  href?: string;
  isButton?: boolean;
  isExternal?: boolean;
};

export type Faq = {
  _type: 'faq';
  title?: string;
  body?: string;
};

export type SocialLink = {
  _type: 'socialLink';
  platform?: 'git-hub' | 'linked-in' | 'facebook' | 'instagram';
  url?: string;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type MediaFolderReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'media.folder';
};

export type MediaFolder = {
  _id: string;
  _type: 'media.folder';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  parent?: MediaFolderReference;
};

export type MediaTag = {
  _id: string;
  _type: 'media.tag';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | CarePlan
  | Slug
  | Page
  | BlockContent
  | Seo
  | Capability
  | Faqs
  | Project
  | SanityImageAssetReference
  | ImageWithAlt
  | Service
  | SiteSetting
  | FooterColumn
  | NavLink
  | Faq
  | SocialLink
  | SanityImageCrop
  | SanityImageHotspot
  | MediaFolderReference
  | MediaFolder
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/query.ts
// Variable: ROOT_LAYOUT_SEO_QUERY
// Query: *[_type == 'siteSetting'][0]{  "title": seo.metaTitle,  "description": seo.metaDescription}
export type ROOT_LAYOUT_SEO_QUERY_RESULT = {
  title: string | null;
  description: string | null;
} | null;

// Source: src/sanity/query.ts
// Variable: CONTACT_US_PAGE_SEO_QUERY
// Query: *[_type == 'page' && slug.current == 'contact-us-page' && type == 'main'][0]{  "title": seo.metaTitle,  "description": seo.metaDescription }
export type CONTACT_US_PAGE_SEO_QUERY_RESULT = {
  title: string | null;
  description: string | null;
} | null;

// Source: src/sanity/query.ts
// Variable: NAV_LINKS_QUERY
// Query: *[_type == 'siteSetting'][0]{  navLinks[]{    _key,    label,    isButton,    isExternal,    href  }}
export type NAV_LINKS_QUERY_RESULT = {
  navLinks: Array<{
    _key: string;
    label: string | null;
    isButton: boolean | null;
    isExternal: boolean | null;
    href: string | null;
  }> | null;
} | null;

// Source: src/sanity/query.ts
// Variable: COMPANY_PAGE_QUERY
// Query: *[_type == 'page' && defined(slug.current) && type == 'utility' && slug.current == $slug][0]{  body,  "slug": slug.current,  "seoTitle": seo.metaTitle,  "seoDescription": seo.metaDescription }
export type COMPANY_PAGE_QUERY_RESULT = {
  body: BlockContent | null;
  slug: string | null;
  seoTitle: string | null;
  seoDescription: string | null;
} | null;

// Source: src/sanity/query.ts
// Variable: ALL_COMPANY_PAGES
// Query: *[_type == 'page' && defined(slug.current) && type == 'utility' ]{  "slug": slug.current, }
export type ALL_COMPANY_PAGES_RESULT = Array<{
  slug: string | null;
}>;

// Source: src/sanity/query.ts
// Variable: FOOTER_QUERY
// Query: *[_type == 'siteSetting'][0]{  "columns": footerColumns[]{    _key,    links[]{      _key,      href,      label    },    title  },  "text": footerText,  "street": contactInfo.street,  "city": contactInfo.city,  "state": contactInfo.state,  "country": contactInfo.country,  "zip": contactInfo.zip,}
export type FOOTER_QUERY_RESULT = {
  columns: Array<{
    _key: string;
    links: Array<{
      _key: string;
      href: string | null;
      label: string | null;
    }> | null;
    title: string | null;
  }> | null;
  text: string | null;
  street: string | null;
  city: string | null;
  state: string | null;
  country: string | null;
  zip: string | null;
} | null;

// Source: src/sanity/query.ts
// Variable: ALL_PRICING_QUERY
// Query: {  "pricing": *[_type == 'carePlan'              && defined(slug.current)]              | order(isPremium asc){                _id,                name,                "slug": slug.current,                excerpt,                pricePerMonth,                "inclusives": inclusive[]{                  _key,                  title                },                "exclusives": exclusive[],                isPremium,              },  "seo": *[_type == 'page'          && slug.current == 'pricing-page'          && type == 'main'][0]{            "title": seo.metaTitle,            "description": seo.metaDescription          }}
export type ALL_PRICING_QUERY_RESULT = {
  pricing: Array<{
    _id: string;
    name: string | null;
    slug: string | null;
    excerpt: string | null;
    pricePerMonth: number | null;
    inclusives: Array<{
      _key: string;
      title: string | null;
    }> | null;
    exclusives: Array<string> | null;
    isPremium: boolean | null;
  }>;
  seo: {
    title: string | null;
    description: string | null;
  } | null;
};

// Query TypeMap
declare global {
  interface SanityQueries {
    '*[_type == \'siteSetting\'][0]{\n  "title": seo.metaTitle,\n  "description": seo.metaDescription\n}': ROOT_LAYOUT_SEO_QUERY_RESULT;
    "*[_type == 'page'\n && slug.current == 'contact-us-page'\n && type == 'main'][0]{\n  \"title\": seo.metaTitle,\n  \"description\": seo.metaDescription\n }": CONTACT_US_PAGE_SEO_QUERY_RESULT;
    "*[_type == 'siteSetting'][0]{\n  navLinks[]{\n    _key,\n    label,\n    isButton,\n    isExternal,\n    href\n  }\n}": NAV_LINKS_QUERY_RESULT;
    '*[_type == \'page\'\n && defined(slug.current)\n && type == \'utility\'\n && slug.current == $slug][0]{\n  body,\n  "slug": slug.current,\n  "seoTitle": seo.metaTitle,\n  "seoDescription": seo.metaDescription\n }': COMPANY_PAGE_QUERY_RESULT;
    "*[_type == 'page'\n && defined(slug.current)\n && type == 'utility'\n ]{\n  \"slug\": slug.current,\n }": ALL_COMPANY_PAGES_RESULT;
    '*[_type == \'siteSetting\'][0]{\n  "columns": footerColumns[]{\n    _key,\n    links[]{\n      _key,\n      href,\n      label\n    },\n    title\n  },\n  "text": footerText,\n  "street": contactInfo.street,\n  "city": contactInfo.city,\n  "state": contactInfo.state,\n  "country": contactInfo.country,\n  "zip": contactInfo.zip,\n}': FOOTER_QUERY_RESULT;
    '{\n  "pricing": *[_type == \'carePlan\'\n              && defined(slug.current)]\n              | order(isPremium asc){\n                _id,\n                name,\n                "slug": slug.current,\n                excerpt,\n                pricePerMonth,\n                "inclusives": inclusive[]{\n                  _key,\n                  title\n                },\n                "exclusives": exclusive[],\n                isPremium,\n              },\n  "seo": *[_type == \'page\'\n          && slug.current == \'pricing-page\'\n          && type == \'main\'][0]{\n            "title": seo.metaTitle,\n            "description": seo.metaDescription\n          }\n}': ALL_PRICING_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module '@sanity/client' {
  interface SanityQueries extends globalThis.SanityQueries {}
}
